### PR TITLE
Update to build on Python 3.10

### PR DESCRIPTION
**Pull request by luciansmith**
Last time we tried this it didn't work, but hopefully things have settled down by now.

### CODE REVIEW

**Comment by luciansmith** [comment]
The mac version now works, but not the Windows nor Linux, for different reasons.

On Windows, it fails because CMake can't find python at all.  On my machine, when NumPy wasn't installed, it behaved this way, but installing numpy didn't help (neither with pip install nor conda install).  I don't know where to go from here.

On Linux, we can't install conda 4.11 because we don't have permission (!).  Maybe this is because of the docker VM or something; the best option seems to be to update the docker image to contain conda 4.11 and numpy.

**Comment by luciansmith** [comment]
@CiaranWelsh : Can you take a look at this?  Also, we should work together to figure out how to move the docker images to the sys-bio account and get instructions on how to update them.

**Comment by CiaranWelsh** [comment]
Yep sure. For owning the docker repo, you just need to build the docker image yourself and upload it to a sys-bio docker hub account. Then you can update azure to use your image instead of mine. Will be able to talk you though it if needed.

**Comment by luciansmith** [comment]
Yeah, I can't actually install docker permanently because it kills VirtualBox, so I never use it.  So a demo would be great!

**Comment by CiaranWelsh** [comment]
I've updated the docker image which exists at ciaranwelsh/roadrunner-manylinux2014-base. To do this I did the following: 

Change the source code manually in the dockerfile to update the miniconda link from this: 
    https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
to
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

find the docker directory
```
cd /mnt/d/roadrunner/roadrunner/docker/roadrunner-manylinux2014-base/
```
Build the docker image. The tag is the name of my dockerhub repo plus the 
name of the docker image. For you, this might be luciansmith/roadrunner-manylinux2014-base if your dockerhub id is "luciansmith". This will take a while (half a day or more)
```
docker build --tag ciaranwelsh/roadrunner-manylinux2014-base .
```

Nnow push to docker using the same tag you used to build. So for me its
```
docker push ciaranwelsh/roadrunner-manylinux2014-base
```

That should be it. Of course you'll need to actually create the dockerhub account that you want to use in future. Also, you might want to consider using one of the mac's that you have lying around which will save you from needing to modify the Windows "hyper-whatever" setting. Let me know if you run into problems.

**Comment by luciansmith** [comment]
Ignoring linux python for now...

**Pull request merged**
