### PR TITLE
Plugin loader macros

### PR DESCRIPTION
**Pull request by adelhpour**
The problem with loading the Python rrplugins in Linux is now fixed by introducing the Poco ClassLoader macros for each plugin.

### CODE REVIEW

**Comment by luciansmith** [comment]
Closing this to see if me creating it instead helps.

**Comment by adelhpour** [comment]
Okay.On Mar 17, 2023, at 10:47 PM, Lucian Smith ***@***.***> wrote:﻿
Closing this to see if me creating it instead helps.

**Comment by luciansmith** [comment]
This got fixed in a different branch eventually, no?

**Comment by adelhpour** [comment]
Closing this PR as it didn’t meet the requirements. Will revisit later if needed.

**Pull request closed without merging**
