### PR TITLE
The feature to get and set parametric stoichiometries is added

### PR DESCRIPTION
**Pull request by adelhpour**
Users can now set and get parameters used to define stoichiometries if the species associated with that parametric stoichiometry appears only once in a reaction. Note that, it is not possible to set and get stoichiometries while conserved moiety is turned on.

### CODE REVIEW

**Comment by luciansmith** [comment]
Oh, stoich(rxn, species) is brilliant.

Also, none of the tests are going to pass because it's trying to download a specific libroadrunner-deps file instead of 'the latest'.  My plan was to investigate this at some point, but if you manage to figure it out before me, go for it! ;-)  An Antimony run went fine, and it also downloads librr-deps, so maybe start with that?  Maybe compare https://github.com/sys-bio/antimony/blob/develop/azure-pipelines.yml with roadrunner's.

**Comment by adelhpour** [comment]
> Oh, stoich(rxn, species) is brilliant.
> 
> Also, none of the tests are going to pass because it's trying to download a specific libroadrunner-deps file instead of 'the latest'. My plan was to investigate this at some point, but if you manage to figure it out before me, go for it! ;-) An Antimony run went fine, and it also downloads librr-deps, so maybe start with that? Maybe compare https://github.com/sys-bio/antimony/blob/develop/azure-pipelines.yml with roadrunner's.

Just did it. Let's see what happens!

**Comment by luciansmith** [comment]
That worked!  And now you hit a bug in conda itself, which I was REALLY HOPING would be fixed by now, because it literally breaks everything.

https://github.com/conda/conda/issues/12531

**Comment by adelhpour** [comment]
> That worked! And now you hit a bug in conda itself, which I was REALLY HOPING would be fixed by now, because it literally breaks everything.
> 
> [conda/conda#12531](https://github.com/conda/conda/issues/12531)

Shall we wait for them to fix it, or we have to do something now?

**Comment by luciansmith** [comment]
github seems to be having connectivity problems right now; the checks had problems just checking out the repository.  I killed the pipeline run; I think if I close and re-open the PR, it'll start it again from scratch.

**Pull request merged**
