### PR TITLE
RRPlugins

### PR DESCRIPTION
**Pull request by debashish05**
This pull request is done under GSoC 2020. Some major points are as follows:
1) This provides rrplugins to build independently of roadrunner. Now change in roadrunner doesn't need to rebuild rrplugins and vice versa. 
2) Add Noise and testModel plugin is ported to this new system.
3) rrVersionsInfo.h file is needed by rrplugins. Earlier roadrunner needs to be installed first then rrplugins need this in the linking stage. But now since rrplugins and roadrunner are the same builds this file needs to present in the source code.
4) Currently, there are folders in rrplugins that are not working that need to be cleaned by me, Eg. rrplguins/Examples.
5) All the plugins are needed to be ported to this new architecture and I am working on it.
6) Currently, by default, this code will not affect roadrunner, and will not included in roadrunner by default. But can be used by turning RRPlugins support while the Cmake step.
7) Modifed the CPython wrapper to make it work in Python 3 for rrplugins.

### CODE REVIEW

**Comment by kirichoi** [comment]
Apart from build issues, there are few other things that needs to be done before merging:
1) Wrapper integration to roadrunner build system
2) Cleaning the source to the rrplugins core

**Comment by debashish05** [comment]
The test model plugin is not working in Linux, because loadSBML is not able to load the XML file. Need to look at the issue. Also, after execution python program, there is an error message "free(): invalid pointer Aborted (core dumped)". This also needs to be fixed. 

For points (1) Integration of both wrapper will a bit tough mainly because of debugging issues in SWIG. For the time being, I am sticking with CPython wrapper and keep the integration of wrapper as the long term goal.
(2) Yes, surely need to look at this issue.

**Comment by luciansmith** [comment]
I looked at all the bits that aren't in the rrplugins/ directory, and there are only a couple changes I would make:

* The rrVersionInfo.h file should not be included:  it's created from the rrVersionInfo.h.in file, instead.
* The rrRoadRunner.cpp differences seem to be entirely 'deleted blank lines' and other whitespace changes.  Those can probably be dropped, but it's not a huge deal either way.

I can make the changes myself if you want.  Thank you!

**Comment by debashish05** [comment]
1) RRPlugins need that header file which is autogenerated at the compile time. Earlier when roadrunner is installed first the rrVersion.h file gets generated first and then we go on building rrplugins. So at compile time rrplugins used to get the rrVersion.h file. But since we are merged two separate processes into one, now at compile time there will be no rrVersion.h for rrplugins. So, it will show error can't open the include file. 
RRPlugins need rrVersion.h because it is using the roadrunner c wrapper file. That's why included that file as a temporary fix. 

**Fix**: Modified the CMakeLists to make it a proper fix. Now we don't need to include the rrVersionInfo.h. 

2) For the second point, I experimented with the main roadrunner as well early on so maybe these changes are because of that. It will be very kind if you can check the blank lines thing. Any more recommendations or updates you want in the code. I have also updated the binaries in the google drive link that I have shared. Thanks for sharing your view regarding the code.

**Comment by debashish05** [comment]
For the second point, I experimented with the main roadrunner as well early on so maybe these changes are because of that. It will be very kind if you can check the blank lines thing. Any more recommendations or updates you want in the code.  I have also updated the binaries in the google drive link that I have shared.

**Comment by debashish05** [comment]
Thank you for fixing this. Anything else from my side, I need to fix it?

**Comment by luciansmith** [comment]
Looks good!  Thank you so much!

**Pull request merged**
