### PR TITLE
Fix for https://github.com/sys-bio/roadrunner/issues/781

### PR DESCRIPTION
**Pull request by luciansmith**
(Also, add 'getHasOnlySubstanceUnits', which I needed for a different problem but am sticking here because lazy.)

This change adds new functions for eigenvalues that return named arrays, and also changes the existing functions to always return complex values instead of changing the return type based on content.

### CODE REVIEW

**Review by CiaranWelsh — COMMENTED** [review]
The changes look good to me, though I can't comment on your swig changes without running the code. 

One nit pick - could we add some tests on the Python end as well? That is, add to or modify the appropriate tests inside "wrappers/Python/roadrunner/testing/python_api_tests.py", shouldn't take too much effort. (side note: this test suite is still a work in progress, hence all the skipped tests. I had planned on coming back to these once all the "easy" tests are written).

**Comment by matthiaskoenig** [comment]
@luciansmith can you merge this in develop?

I am not sure if the `getHasOnlySubstanceUnits` is exported in the python SWIG interface. I would need this functionality for the SED-ML symbol (amount/concentration) support.

**Comment by luciansmith** [comment]
Sure--I was leaving this so that I didn't forget to add tests, but I'll add that as a separate issue.

(And yes, it's in Python--I'm sure I needed it for the same thing you need it for!)

**Comment by matthiaskoenig** [comment]
@luciansmith Thanks. I could get this installed via the build artifacts.
But I only see the `setHasOnlySubstanceUnits` not the `getHasOnlySubstanceUnits` exposed on the RoadRunner object. I think the getter is missing form the swig interface.

**Pull request merged**
