### PR TITLE
Added getCC test/minor fixes

### PR DESCRIPTION
**Pull request by kirichoi**
Added getCC test to roadrunner test suite. Changes handling of global variables.
Jacobian_1.rrtest will out the getCC method.

### CODE REVIEW

**Comment by luciansmith** [comment]
Don't forget to add a corresponding test to the roadrunner C tests--I think if you add something to an .rrtest file it doesn't know about, it'll fail, complaining that it doesn't know about that test.

**Comment by kirichoi** [comment]
Updated with getCC C tests.

**Comment by 0u812** [comment]
I'm getting some weird failures in the `SCALED_CONCENTRATION_CONTROL_MATRIX` test:
```
<test suite="TEST_MODEL" name="SCALED_CONCENTRATION_CONTROL_MATRIX" time="0"><failure message="Suite_TestModel.cpp(145) : Expected 0.85479 +/- 0.000170958 but was 1.70958"/><failure message="Suite_TestModel.cpp(145) : Expected 0.346536 +/- 6.93073e-05 but was 0.693073"/><failure message="Suite_TestModel.cpp(145) : Expected -1.03239 +/- 0.000206478 but was -2.06478"/><failure message="Suite_TestModel.cpp(145) : Expected -0.168936 +/- 3.37873e-05 but was -0.337873"/><failure message="Suite_TestModel.cpp(145) : Expected 0.85479 +/- 0.000170958 but was 1.70958"/><failure message="Suite_TestModel.cpp(145) : Expected 0.049239 +/- 9.84782e-06 but was 0.0984781"/><failure message="Suite_TestModel.cpp(145) : Expected 0.0824754 +/- 1.64951e-05 but was 0.164951"/><failure message="Suite_TestModel.cpp(145) : Expected -0.986504 +/- 0.000197301 but was -1.97301"/></test>
```

**Comment by 0u812** [comment]
Discussion continued in #139. It's the same problem with the jacobian1 model. May need to keep this open until bugs are identified.

**Comment by 0u812** [comment]
Merged in manually in 0e5b574

**Pull request closed without merging**
