### PR TITLE
Merge latest updates for release.

### PR DESCRIPTION
**Pull request by luciansmith**

### CODE REVIEW

**Comment by CiaranWelsh** [comment]
I know having to do the experimental release as well as the real release is annoying, but we should probably stick to the develop -> experimental-release -> release workflow. Also, the `Experimental = True` flag is on in this PR anyway so you won't be able to push to libroadrunner on pypi (only libroadrunner-experimental). 

I'd cancel this and then do the PR from experimental-release into release, once the develop -> experimental has been merged. 

(sorry for the faff, I thought the experimental release idea was a good one at the time...)

**Comment by luciansmith** [comment]
We don't need the experimental-release branch; we can just get those wheels from develop.

**Comment by luciansmith** [comment]
Also, wait--the whole point is that Release is identical to develop except that the experimental flag is off.  Git doesn't like this and wants you to click 'update branch', but as long as you don't do that, you should be fine.  I thought!

**Comment by CiaranWelsh** [comment]
> We don't need the experimental-release branch; we can just get those wheels from develop.

Makes sense, I don’t know why I didn’t think of this.

**Comment by luciansmith** [comment]
OK, I just checked, and yes:  the artifacts from this merge do indeed have the experimental flag off:

https://dev.azure.com/TheRoadrunnerProject/roadrunner/_build/results?buildId=1398&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by luciansmith** [comment]
(Also, I cancelled everything to get the numpy requirement updated first.)

**Comment by CiaranWelsh** [comment]
Okay it sounds like you have it covered for now. If there are still builds not push to pypi by tomorrow morning I’ll do it first thing. 

(Feel free to cancel PRs I created etc.)

**Comment by luciansmith** [comment]
Sounds good!  I think I can manage to get everything out.

If you wouldn't mind looking at https://github.com/sys-bio/roadrunner/branches/all and deleting any branch you were using and don't need any more, that'd be great, too.

**Pull request merged**
