### PR TITLE
Add methods for getting independent and dependent floating species am…

### PR DESCRIPTION
**Pull request by samuels342**
…ounts and concentrations as a vector or named array

### CODE REVIEW

**Comment by luciansmith** [comment]
I found and fixed a variety of issues with this; the one thing I didn't fix so far is the C++ tests, which weren't being run.  Now that they're running, they're failing.

There's two issues here:  one is that you have to turn on conserved moiety analysis to split the two species into one dependent and one independent.  The other is that the names in the named array aren't being checked, and should be.  As mentioned in the commit message, I can do this myself if you're already gone, but if you're still around, feel free to make the fixes (and look to see what I changed, just for future reference).

**Comment by samuels342** [comment]
Thank you for the fixes. Sorry I didn’t realize there were errors. I will not be able to make the changes unfortunately but I will look at it for my own reference.

Thank you sincerely for all of your help this year. It’s been a pleasure to work at the Sauro lab with you. Have a great summer :)

**Comment by luciansmith** [comment]
And thank you for your work!  I enjoyed working with you as well.  Best of luck in your future endeavors!

**Comment by luciansmith** [comment]
This was more complicated than it had any right to be, but the new version now works.  The only issue is that we've actually changed the behavior of a couple python functions, but hopefully for the better.

**Pull request merged**
