### PR TITLE
make ncurses linking static

### PR DESCRIPTION
**Pull request by evilnose**
ncurses is a dependency of LLVM on linux. Since Ubuntu 2020 ncurses-6.0 is included by default instead of 5.0, so linking dynamically on linux cannot work for all linux platforms.

I've added minor changes to FindLLVM.cmake so that cmake is forced to link against libncurses.a when building on linux.

### CODE REVIEW

**Comment by luciansmith** [comment]
Looks like this worked on Windows, but not mac or linux.  (Which is weird, since you designed it for linux!)

**Comment by evilnose** [comment]
Ah, right. Looking at the error log it's because libncurses.a is not installed. I think we just need to install ncurses-static in these cases.

Windows worked probably because it could skip ncurses altogether.

**Comment by luciansmith** [comment]
Do you know how to tell azure to install ncurses?  I can try to work on it
or try to pull in Ciaran if not.

-Lucian

**Comment by evilnose** [comment]
I've never worked with azure, so I have no idea, sorry.

**Comment by CiaranWelsh** [comment]
Has this PR gone stale now?

**Comment by CiaranWelsh** [comment]
Closed due to inactivity. Plus I have installed ncurses in the manylinux2014 docker image for roadrunner, so I think that resolved this problem anyway.

**Comment by CiaranWelsh** [comment]
#755 Deals with this.

**Pull request closed without merging**
