### PR TITLE
Proposed workaround for issue #373

### PR DESCRIPTION
**Pull request by kirichoi**

### CODE REVIEW

**Comment by 0u812** [comment]
Thanks Kiri! Did you already check that this resets the conserved totals or should I do that?

**Comment by hsauro** [comment]
Make sure you add regression tests for these.

Herbert

**Comment by kirichoi** [comment]
It does reset the conserved totals but I wanted to hear some opinions on whether the workaround could break other things.

**Comment by 0u812** [comment]
Let me try to figure out if DEPENDENT_INITIAL_GLOBAL_PARAMETER can apply to anything other than conserved totals.

**Pull request merged**
