### PR TITLE
Test files for python are scattered--collect them in one place.

### PR DESCRIPTION
**Pull request by luciansmith**

### CODE REVIEW

**Comment by CiaranWelsh** [comment]
FYI: I’ve been organising tests by feature rather than language, which is why you’ll find .py test files under test subfolders. Doesn’t make a huge difference but it made more sense to me whilst writing them.

**Comment by luciansmith** [comment]
That makes sense for me for the C++ tests, because they're then collected and run together.  But the state of the art for python unit tests seems to be 'run everything in this directory', which also seems to normally be the 'tests' subdirectory of the project itself (including subdirectories) so I think moving them is the way to go?  This would let us run the tests either from the source code or from the installation.  I think if they're scattered, they're harder to run from the source code.

I started off moving everything into the wrappers/python/roadrunner/testing/ directory, but after mucking about with that a bit, I think it makes a bit more sense to take over the test/python/ directory instead, and rename that directory in the installation to site-packages/roadrunner/tests/  I do like having them all in a single directory in both places, though.  Opinions?

**Comment by CiaranWelsh** [comment]
> This would let us run the tests either from the source code or from the installation

Not exactly. I can run tests from source folder using clion, because it automatically adds "content roots" and "source roots" to the PYTHON_PATH. However, outside of CLion you still need to add the path to the roadrunner site-packages, otherwise the tests wont find roadrunner (or worse finds another local installation of roadrunner in your python site-packages). Using the build tree is a better idea, and in this case all the tests get collected together and put into the "testing" folder anyway.  

Personally I like to have the tests split by feature in the source directory regardless of language, but its not a big deal and makes little difference in practice - If you prefer to move them to "test/Python/..." that's fine by me.

>and rename that directory in the installation to site-packages/roadrunner/tests/ 

Yep, totally agree. And whilst we're at it we could delete the folders which are called "testing" under the source directory which seems to be Andy working out how to use llvm like 10 years ago.

**Review by CiaranWelsh — COMMENTED** [review]
Yep, that’ll be the pickle tests. Something hangs when run with unit test. I’ve fixed this on my branch so you can go ahead and comment out all the pickle tests on yours, l try and get my work integrated into the main branch now.

**Comment by luciansmith** [comment]
Actually, the pickle tests were already commented out!  This has to do with the revamped pytest now running things that ctest also runs... at least I think that's the issue.  I've also added in the stochastic test suite tests for the first time, which take a chunk of time on their own (and were being incorporated twice, once with ctest and once with run-pytest-tests).

**Comment by luciansmith** [comment]
Wait, no, you're right--looks like I uncommented everything earlier and the pickle tests slipped back in.  But they weren't the problem that time 'round; the problem was long tests being run twice.

**Pull request merged**
